{{- if .Values.bootnode.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-bootnode
  namespace: {{ .Values.namespace }}
  labels:
    app: nethermind
    component: bootnode
spec:
  serviceName: {{ .Release.Name }}-bootnode
  replicas: 1
  selector:
    matchLabels:
      app: nethermind
      component: bootnode
  template:
    metadata:
      labels:
        app: nethermind
        component: bootnode
    spec:
      containers:
      - name: nethermind
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NETHERMIND_CONFIG
          value: "goerli"
        - name: NETHERMIND_NETWORK_DISCOVERYPORT
          value: "30303"
        - name: NETHERMIND_NETWORK_P2PPORT
          value: "30303"
        - name: NETHERMIND_JSONRPC_ENABLED
          value: "true"
        - name: NETHERMIND_JSONRPC_HOST
          value: "0.0.0.0"
        - name: NETHERMIND_JSONRPC_PORT
          value: "8545"
        - name: NETHERMIND_NETWORK_NETWORKID
          value: "{{ .Values.networkId }}"
        - name: NETHERMIND_NETWORK_CHAINID
          value: "{{ .Values.chainId }}"
        ports:
        - name: discovery
          containerPort: 30303
          protocol: UDP
        - name: p2p
          containerPort: 30303
          protocol: TCP
        - name: json-rpc
          containerPort: 8545
        resources:
          {{- toYaml .Values.bootnode.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bootnode
  namespace: {{ .Values.namespace }}
  labels:
    app: nethermind
    component: bootnode
spec:
  ports:
  - name: discovery
    port: 30303
    protocol: UDP
  - name: p2p
    port: 30303
    protocol: TCP
  - name: json-rpc
    port: 8545
  selector:
    app: nethermind
    component: bootnode
{{- end }} 