apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-miner
  namespace: {{ .Values.namespace }}
  labels:
    app: nethermind
    component: miner
spec:
  serviceName: {{ .Release.Name }}-miner
  replicas: {{ .Values.miners.replicas }}
  selector:
    matchLabels:
      app: nethermind
      component: miner
  template:
    metadata:
      labels:
        app: nethermind
        component: miner
    spec:
      containers:
      - name: nethermind
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NETHERMIND_CONFIG
          value: "goerli"
        - name: NETHERMIND_NETWORK_DISCOVERYPORT
          value: "30303"
        - name: NETHERMIND_NETWORK_P2PPORT
          value: "30303"
        - name: NETHERMIND_JSONRPC_ENABLED
          value: "true"
        - name: NETHERMIND_JSONRPC_HOST
          value: "0.0.0.0"
        - name: NETHERMIND_JSONRPC_PORT
          value: "8545"
        - name: NETHERMIND_NETWORK_NETWORKID
          value: "{{ .Values.networkId }}"
        - name: NETHERMIND_NETWORK_CHAINID
          value: "{{ .Values.chainId }}"
        - name: NETHERMIND_MINING_ENABLED
          value: "true"
        - name: NETHERMIND_DISCOVERYNEWPEERS
          value: "true"
        - name: NETHERMIND_SYNC_FASTSYNC
          value: "false"
        - name: NETHERMIND_STATICNODESPATH
          value: "/nethermind/Data/static-nodes.json"
        ports:
        - name: discovery
          containerPort: 30303
          protocol: UDP
        - name: p2p
          containerPort: 30303
          protocol: TCP
        - name: json-rpc
          containerPort: 8545
        resources:
          {{- toYaml .Values.miners.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-miner
  namespace: {{ .Values.namespace }}
  labels:
    app: nethermind
    component: miner
spec:
  ports:
  - name: discovery
    port: 30303
    protocol: UDP
  - name: p2p
    port: 30303
    protocol: TCP
  - name: json-rpc
    port: 8545
  selector:
    app: nethermind
    component: miner 