grafana:
  adminPassword: ${grafana_admin_password}
  persistence:
    enabled: true
    storageClassName: standard
    size: 10Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-operated.${namespace}.svc.cluster.local:9090
          access: proxy
          isDefault: true
          editable: false
  namespaceOverride: ${namespace}

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ${prometheus_storage_class}
          resources:
            requests:
              storage: ${prometheus_storage_size}
  namespaceOverride: ${namespace}

alertmanager:
  enabled: ${alertmanager_enabled}
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 5Gi
  namespaceOverride: ${namespace}

# Ensure all components are installed in the monitoring namespace
namespace: ${namespace} 