image:
  repository: europe-west1-docker.pkg.dev/play-project-325908/ledgerndary/nethermind
  tag: b53bac2bcf6969ea9da4bb5a1beed48484198baa
  # pullPolicy: Always
  pullPolicy: Always
bootnode:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
miners:
  replicas: 2
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
networkId: 1337
chainId: 1337
genesis:
  difficulty: "1"
  gasLimit: "8000000"
  coinbase: "0x0000000000000000000000000000000000000000"
  timestamp: "0x00"
  extraData: "0x"
  alloc:
    "0x0000000000000000000000000000000000000000":
      balance: "1000000000000000000000000000"
